GeoStat-Framework/GSTools

AUTHORS.md
README.md
docs/requirements.txt
docs/source/index.rst
docs/source/tutorial_01_srf.rst
examples/06_unstr_srf_export.py
gstools/__init__.py
gstools/field/base.py
gstools/tools/__init__.py
gstools/tools/export.py
requirements.txt
setup.py
tests/test_export.py

-----
This PR uses [PyVista](http://docs.pyvista.org) for creating VTK datasets in Python for immediate plotting. The `pyevtk`  export code is still present to allow users to save VTK files in any Python environment. PyVista is a heavy dependency so these additions are implemented as optional features.
When complete, this will need to use "Squash and Merge"
-----
PyVista allows you to create VTK data objects in memory really easily instead of saving them out to static files. *Why might you want VTK/PyVista meshes in Python?* So you can skip saving VTK files and visualize the datasets right in Python! Check out this example:
```py
import pyvista as pv
from gstools import SRF, Gaussian
import matplotlib.pyplot as pt
x = y = z = range(100)
model = Gaussian(dim=3, var=0.6, len_scale=20)
srf = …
```

Add PyVista for 3D plotting in Python

---

gstools/__init__.py

Maybe this is coming a bit late, but we should soon make a new release with the deprecation warnings of this pull request and give our users a head start with upgrading their Python versions.
For the discussion about dropping the support, see issue #40.

Print deprecation warnings for Python 2.7 and 3.4

---

docs/source/tutorial_02_cov.rst
gstools/covmodel/base.py

At the moment there was no warning if a user set an additional parameter while creating a covariance model.
This can be fatal if:
- a model needs an additional parameter, but there is no default value and no value was given with instantiation
- a user had a typo in the standard parameters (See #45)
This PR adds a warning, when an optional parameter was given, that has no predefined default value. Also the documentation was updated accordingly.

CovModel: check optional arguments and warn if unknown

---

.travis.yml

Since PR from outside have no access to the PyPI password on travis, this modification will skip deployment for PRs.

CI: no deploy for pull requests

---

gstools/covmodel/base.py

This should be a speedup for calculating the spectral density of an arbitrary cov-model.
The value ``N=200`` is now default (before 1000). See here for explanation: [hankel-doc](https://hankel.readthedocs.io/en/latest/demos/testing_forward_and_inverse_transforms.html#Changing-N)

Hankel update

---

.travis.yml
docs/source/index.rst
gstools/__init__.py
gstools/_version.py
setup.py

In this PR an automated versioning by `setuptools_scm` is proposed.
This means:
- on release, the version is obtained from the git-tag
- for every development version the version is determined from the last git-tag
See: https://test.pypi.org/project/gstools/1.1.2.dev155/
- a new `_version.py` is written on every install of the package
- if no version is present a default version of `"0.0.0.dev0"` is set
With this feature, we don't need manual version bumps anymore and the `devN` versions are automatically increased with each commit, so we don't get deploy conflicts with `test.pypi`

Automated versioning

---

.travis.yml
examples/02_cov_model/00_intro.py
examples/02_cov_model/05_additional_para.py
examples/02_cov_model/06_fitting_para_ranges.py
examples/03_variogram/01_variogram_estimation.py
examples/03_variogram/02_find_best_model.py
gstools/covmodel/base.py
gstools/covmodel/fit.py
gstools/covmodel/models.py
gstools/covmodel/plot.py
gstools/covmodel/tools.py
gstools/field/base.py
gstools/field/generator.py
gstools/field/srf.py
gstools/krige/base.py
gstools/krige/methods.py
gstools/random/rng.py
gstools/random/tools.py
gstools/tools/export.py
gstools/variogram/estimator.pyx
gstools/variogram/variogram.py
tests/test_covmodel.py
tests/test_variogram_structured.py

This PR introduces an updated variogram fitting routine:
- fixing sill possible now
- `loss` is now selectable for smoother handling of outliers
- r2 score can now be returned to get an impression of the goodness of fitting
- weights can be passed
- instead of deselecting parameters, one can also give fix values for each parameter
Also:
- minor doc fixes
- skip travis builds for PRs from our own repo
- better setting of bounds in CovModel

Variogram fitting update

---

examples/05_kriging/01_ordinary_kriging.py
examples/05_kriging/05_universal_kriging.py
examples/05_kriging/08_measurement_errors.py
examples/05_kriging/09_pseudo_inverse.py
examples/05_kriging/README.rst
examples/06_conditioned_fields/00_condition_ensemble.py
gstools/field/base.py
gstools/field/condition.py
gstools/krige/__init__.py
gstools/krige/base.py
gstools/krige/methods.py
gstools/tools/__init__.py
gstools/tools/special.py
tests/test_krige.py

Closes #79 
Fixes #89 
Here comes the great unification of our `krige` submodule:
PS: I needed to create a new PR, since there were some commits in the branch, that weren't recognized by the last PR.

Krige unification

---

gstools/covmodel/base.py

I just wanted to make a pretty plot of a 3d field and instead of rotating the camera, I wanted to simply rotate the field.
This is not possible if the field is isotropic.
Of course, from a stochastic point of view, it doesn't make sense to rotate a field, if it is isotropic. But this is a restriction, which is not necessary, especially if one is working with a single realisation.
Especially for nice plotting, I suggest to simply remove the check for isotropicity, as seen in the diff.

Isotropic rotation not possible

---

gstools/variogram/estimator.pyx
gstools/variogram/variogram.py
tests/test_variogram_unstructured.py

@MuellerSeb @LSchueler I finished implementing the angle dependent variogram calculation and implemented a few test cases. Calculation is quasi pure C as soon as the calculation arrives at the calculation heavy loops. Defaults for parameters were chosen in order to preserve original behavior and the implementation should add no computational overhead if no angles are requested.
Can one of you do a code review and look at the test cases? 
Tests passed on my system without a problem. 
```
(base) C:\Users\tobia\source\repos\GSTools>python tests/test_variogram_unstructured.py TestVariogramUnstructured.test_angles
.
----------------------------------------------------------------------
Ran 1 test in 0.003s
OK
```
Test values were generated like this:
```python
import numpy as np
import gstools …
```

Implemented directional variograms for `unstructured`

---

.travis.yml
gstools/covmodel/base.py
gstools/krige/base.py
setup.py

This PR introduces wheels for Python 3.9.
In addition, pushes to `test.pypi.org` are now only done for pushes to `master` or `develop`.
Also a `FutureWarning` from numpy for element wise comparison of arrays is fixed.

CI update: provide Python 3.9 wheels

---

gstools/covmodel/base.py

To be deterministic `CovModel.opt_arg` should be sorted by name.
Closes #103

CovModel: sort opt_arg

---

gstools/covmodel/fit.py

In case `weights` are given as numpy array, we need to prevent comparison to a string.

CovModel.fit: check if weights are given as a string to prevent numpy comparison errors in the future

---

.github/workflows/main.yml

- rewrite triggers
- only master and develop are running
- only PRs to develop (all origins)
- workflow_dispatch fix
- pin version of cibuildwheel
- test.pypi for develop and master

minor CI fixes

---

.github/workflows/main.yml

The `build_sdist` job in the actions script uploads the artifact for every Python version. Often this works without problems, but sometimes it comes to errors and the artifact is not created.
The reason why I keep the sdist creation with all Python versions is to test GSTools without OpenMP support.
This PR is a draft, but the only way to kick off the actions.

CI: The sdists should only be uploaded once to the artifact

---

.github/workflows/main.yml

coveralls-python 3.0 broke our GH-Actions workflow.
See: https://github.com/coveralls-clients/coveralls-python/issues/251

Coveralls 3.0 bugfix

---

README.md

Since `develop` is the standard branch now, we should display badges related to develop.

README: badges from develop

---

README.md
docs/source/conf.py
docs/source/index.rst
docs/source/tutorials.rst
examples/00_misc/03_precipitation.py
examples/09_spatio_temporal/01_precip_1d.py
examples/09_spatio_temporal/02_precip_2d.py
examples/09_spatio_temporal/README.rst

I've updated the precipitation example to now show the time evolution of the 2D P-field as an animated figure.

Replace pyvista 3d plot with matplotlib animation in Precip example

---

gstools/covmodel/base.py
gstools/covmodel/fit.py
tests/test_normalize.py

This PR adds the following changes:
1. `init_guess` can now be given as a dictionary to `CovModel.fit_variogram` specifying initial values given per parameter name
- additional "default" can be set to "default" or "current" to handle unspecified parameters
- this "default" will be "default" by default
2. initial guess for `len_scale` will be the mean of given bin centers to get correct order of magnitude (fixing #143 and #144)
3. initial guess for `var` and `nugget` will be the mean of the given variogram values to get correct order of magnitude

Update init_guess in variogram fitting

---

gstools/covmodel/models.py
gstools/covmodel/tpl_models.py

Some models with shape parameters could run into numerical errors during variogram fitting, since their shape parameters had no upper bound.
Namely:
- TPLSimple
- SuperSpherical
- JBessel
- Rational
The new default upper bound for the shape parameter of these models is `50`. (Can still be changed by the user)

CovModels: limit exponent shape parameters to 50 to prevent numerical errors

---

.github/workflows/main.yml
gstools/__init__.py
gstools/covmodel/base.py
gstools/covmodel/fit.py
gstools/covmodel/plot.py
gstools/covmodel/tools.py
gstools/field/base.py
gstools/field/cond_srf.py
gstools/field/generator.py
gstools/field/plot.py
gstools/field/srf.py
gstools/field/tools.py
gstools/normalizer/base.py
gstools/random/rng.py
gstools/random/tools.py
gstools/tools/geometric.py
gstools/tools/misc.py
gstools/variogram/variogram.py
setup.py

Python 3.5 had its EOL in September 2020 and Ubuntu 16.04 LTS (where Python 3.5 was installed by default) has its End of Standard Support in April 2021. Let's drop support now.
Changes:
- Use `ModuleNotFoundError` when version file could not be found (was not present in py35)
- remove metaclass hack for py35 in `CovModel`
- Use new Github action for `cibuildwheel`
- update setup requirement versions for wheels built: `numpy==1.19.* cython==0.29.*`
- pin version for pypi gh-action

Drop Python 3.5 support and update CI

---

tests/test_variogram_structured.py
tests/test_variogram_unstructured.py

`np.int` will disappear in the future: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Tests: remove tests with np.int which is a deprecated alias for buitin int

---

MANIFEST.in

update `MANIFEST.in` to only include necessary files (gstools, tests, LICENSE, README.md, pyproject.toml, setup.py, setup.cfg) and to exclude docs.

sdist: only include necessary files and tests (no doc)

---

CHANGELOG.md
gstools/covmodel/base.py
gstools/covmodel/tools.py

This line of code generated an Error with `gstools==1.3.0rc2`:
```python
import gstools as gs
print(gs.Matern(nugget=0))
```
```bash
ValueError: Precision not allowed in integer format specifier
```
Reason: `nugget` was never converted to `float` internally and is stored as `int` (which is totally fine for all calculations), but the printing routine tries to format it as float.
This PR solves this problem and adds some minor additions:
- `rescale` was not setable after the model was instantiated: added `rescale.setter`
- `rescale` didn't show up in the `repr` string: fixed if rescale is not the default value
- `anis` and `angles` where always showing up also for isotropic and unrotated models: fixed
This means, the repr is the exact init sequence to create a model:
```python
from gstools …
```

Covmodel arg bugfix: Always convert nugget to float

---

gstools/normalizer/tools.py
gstools/variogram/variogram.py
tests/test_normalize.py

This PR adds optional return of `normalizer` in `vario_estimate` when `fit_normalizer=True`.
Closes: #161

return fitted normalizer

---

examples/05_kriging/02_pykrige_interface.py
gstools/krige/base.py
gstools/krige/methods.py

This PR updates the PyKrige interface example and replaces the `pseudo_inv_type` options (`1, 2, 3`) in all Kriging routines with more descriptive ones to be in line with the settings in PyKrige:
```
pseudo_inv_type : :class:`str` or :any:`callable`, optional
Here you can select the algorithm to compute the pseudo-inverse matrix:
* `"pinv"`: use `pinv` from `scipy` which uses `lstsq`
* `"pinv2"`: use `pinv2` from `scipy` which uses `SVD`
* `"pinvh"`: use `pinvh` from `scipy` which uses eigen-values
If you want to use another routine to invert the kriging matrix,
you can pass a callable which takes a matrix and returns the inverse.
Default: `"pinv"`
```
See:
- https://github.com/GeoStat-Framework/PyKrige/issues/124
- https://github.com/GeoStat-Framework/PyKrige/pull/125
- …

Krige: Adapting to PyKrige

---

.github/workflows/main.yml
CHANGELOG.md
CONTRIBUTING.md
gstools/covmodel/base.py
gstools/covmodel/fit.py
gstools/covmodel/models.py
gstools/covmodel/plot.py
gstools/covmodel/tpl_models.py
gstools/field/base.py
gstools/field/cond_srf.py
gstools/field/generator.py
gstools/field/plot.py
gstools/field/srf.py
gstools/field/tools.py
gstools/field/upscaling.py
gstools/krige/base.py
gstools/normalizer/base.py
gstools/normalizer/methods.py
gstools/normalizer/tools.py
gstools/random/rng.py
gstools/random/tools.py
gstools/tools/export.py
gstools/tools/geometric.py
gstools/tools/misc.py
gstools/tools/special.py
gstools/transform/field.py
gstools/variogram/binning.py
gstools/variogram/variogram.py
pyproject.toml

... I've done it. Pylint is a pain, but a good one.
I created a setup for Pylint in `pyproject.toml` that should warn us about bad practice. I added a new stage in CI to check pylint.
Certain Pylint rules are disabled per file, where it makes sence (at least for me).
It helped me figure out all of the circular imports (see #24). Especially the matplotlib imports are now in a try block and later on deferred.
All remaining pylint warnings were sorted out here.

Pylint fixes

---

pyproject.toml

Closes #164 
Use the meta package for numpy as a build dep: https://github.com/scipy/oldest-supported-numpy
See:
https://scikit-hep.org/developer/packaging#special-additions-numpy
The reason to use the oldest available Numpy version as a build-time dependency is because of ABI compatibility. Binaries compiled with old Numpy versions are binary compatible with newer Numpy versions, but not vice versa.

build: use oldest-supported-numpy

---

CHANGELOG.md
examples/00_misc/05_standalone_field.py
gstools/field/base.py
gstools/field/cond_srf.py
gstools/field/plot.py
tests/test_field.py

Minor update to the `Field` class to enable standalone usage: 
- enable standalone use with given `dim`
- add `points` method to generate field on a point list (transposed unstructured pos tuple as used in many other packages (e.g. PyVista))
- add `latlon` property
- better doc ref to `__call__`
This was a low hanging fruit. Now `Field` can be used to display and export arbitrary n-d point data.

Field: enable standalone use

---

.github/workflows/main.yml

cibuildwheel is now part of pypa:
https://github.com/pypa/cibuildwheel

Use new cibuildwheel action from pypa

---

.github/workflows/main.yml
CHANGELOG.md
gstools/covmodel/base.py
gstools/covmodel/tools.py
gstools/random/rng.py
setup.cfg

Closes #183 
- `sampler.run_mcmc()` needs `nsteps` as integer since `emcee v3.1` (#183)
- PyLint C0206 was added with v2.9
- all dependencies have fixed major version now
- minor tweak in CI to better show the complains of black if there are any

[Bug-Fix] Dependency updates (emcee v3.1, Pylint v2.9)

---

CHANGELOG.md
gstools/krige/base.py
gstools/krige/methods.py
gstools/krige/tools.py

Since the variogram estimation routines ignore nan-data as well as the normalizers, kriging should do that, too.

Krige: filter out nan values from cond_val

---

gstools/covmodel/tools.py
gstools/field/base.py
gstools/field/cond_srf.py
gstools/field/generator.py
gstools/field/srf.py
gstools/field/tools.py
gstools/krige/base.py
gstools/normalizer/base.py

Pylint 2.11 added a checker for f-strings (https://github.com/PyCQA/pylint/pull/4796).
Since we only support python >= 3.6 we should use f-strings where possible.

Pylint: use f-strings where possible

---

src/gstools/krige/base.py
src/gstools/krige/methods.py

With Scipy v1.9 GSTools fails to import `pinv2`, as reported in #246 .
According to the [PR](https://github.com/scipy/scipy/pull/13831) both methods `pinv` and `pinv2` have been using the same algorithms for a long time. Thus, I simply deleted the option `pinv2`.

Remove deprecated scipy method pinv2

---

src/gstools/krige/base.py
src/gstools/krige/methods.py
tests/test_transform.py

Some tests are failing in PR #247 due to very small discrepancies (~10e-16) in floating point comparisons. An approximate comparison is the better test.

Change float comparison in tests

---

src/gstools/covmodel/base.py

PyKrige was not able to use geographical coordinates with a GSTools CovModel. This is the GSTools part of the fix.
See: https://github.com/GeoStat-Framework/PyKrige/issues/217 and https://github.com/GeoStat-Framework/GSTools/issues/235

pykrige: fix passed variogram in case of geo-coord

---

src/gstools/covmodel/base.py
src/gstools/covmodel/fit.py
src/gstools/covmodel/models.py
src/gstools/covmodel/plot.py
src/gstools/covmodel/tools.py
src/gstools/field/base.py
src/gstools/field/cond_srf.py
src/gstools/field/generator.py
src/gstools/field/srf.py
src/gstools/field/tools.py
src/gstools/field/upscaling.py
src/gstools/krige/base.py
src/gstools/krige/methods.py
src/gstools/normalizer/base.py
src/gstools/normalizer/tools.py
src/gstools/random/tools.py
src/gstools/tools/misc.py
src/gstools/tools/special.py
src/gstools/transform/array.py
src/gstools/transform/field.py
src/gstools/variogram/variogram.py

Lots of small readability fixes focused on the `src/.py` path. 
If any changes are needed, please let me know.
Best,
Ryan

refactor(src): readability improvements

---

src/gstools/field/generator.py

The abstract `__init__` was missing in the abstract generator base class.

Generator: add abstract __init__

---

src/gstools/__init__.py
src/gstools/covmodel/base.py
src/gstools/variogram/estimator.pyx
tests/test_covmodel.py

Cherry picks from #243 to be included in v1.4:
- add bounds checks for optional arguments when resetting by class attribute
- Cython: solve -Wsometimes-uninitialized warning
- minor coverage improvements

Cherry picks minor fixes for v1.4

---

src/gstools/field/plot.py

We had a long standing bug in the used matplotlib sliders in the nD viewers as seen here:
https://geostat-framework.readthedocs.io/projects/gstools/en/v1.4.0/examples/01_random_field/07_higher_dimensions.html

Field.plot: solve long-standing mpl slider bug

---

.git_archival.txt
.gitattributes
.github/workflows/main.yml
.readthedocs.yml
pyproject.toml

- update build requirements
- add CI builds/tests for python 3.11
- setuptools_scm v7: add [archive support](https://github.com/pypa/setuptools_scm#builtin-mechanisms-for-obtaining-version-numbers)
- update readthedocs python version to 3.8

Add Python 3.11 and git-archive support

---

examples/02_cov_model/README.rst
src/gstools/__init__.py
src/gstools/covmodel/__init__.py
src/gstools/covmodel/models.py
tests/test_covmodel.py

- adding a new model derived from the Exponential Integral named `Integral`
- fix approximation of Matern spectrum for big `nu`

Add: (Exponential-)Integral model

---

CHANGELOG.md
README.md
docs/source/index.rst
examples/03_variogram/06_auto_bin_latlon.py
examples/08_geo_coordinates/00_field_generation.py
examples/08_geo_coordinates/01_dwd_krige.py
examples/08_geo_coordinates/README.rst
examples/09_spatio_temporal/01_precip_1d.py
examples/09_spatio_temporal/02_precip_2d.py
examples/09_spatio_temporal/03_geografic_coordinates.py
examples/09_spatio_temporal/03_geographic_coordinates.py
examples/09_spatio_temporal/README.rst
pyproject.toml
src/gstools/__init__.py
src/gstools/covmodel/base.py
src/gstools/covmodel/fit.py
src/gstools/covmodel/plot.py
src/gstools/covmodel/tools.py
src/gstools/field/base.py
src/gstools/field/plot.py
src/gstools/krige/base.py
src/gstools/krige/methods.py
src/gstools/tools/__init__.py
src/gstools/tools/geometric.py
src/gstools/transform/field.py
src/gstools/variogram/binning.py
src/gstools/variogram/variogram.py
tests/test_krige.py
tests/test_latlon.py
tests/test_temporal.py

Closes #223, #282
This PR adds a boolean `temporal` and `spatial_dim` attribute to the CovModel class as well as `geo_scale` to CovModel and vario_estimate.
Setting `temporal=True` indicates that the model should be seen as a metric spatio-temporal model. This was possible before by increasing the model dimension by one but this feature basically enables using spatio-temporal model with latlon coordinates. `spatial_dim` was added so the spatial dimension could be set explicitly and not implicitly by increasing only `dim` by 1.
Also a `geo_scale` attribute was added to be able to get meaningful length-scales and bins for latlon models. Before we always used the `rescale` attribute to do that, but that was rather a hack. Now both can be used to set the sphere radius and to rescale the …

Add 'temporal', 'spatial_dim' and 'geo_scale' attributes to Covmodel

---

src/gstools/field/generator.py
tests/test_randmeth.py

Closes #270 
Also makes all arguments after `model` in the generators key-word-only.

Generator: remove 'verbose'

---

src/gstools/transform/array.py
src/gstools/transform/field.py

Closes #300 
pylint/black fixes cherry-picked from #308

Update uniform trans

---

.github/workflows/main.yml
.readthedocs.yml
CHANGELOG.md
pyproject.toml
src/gstools/field/summator.pyx
src/gstools/krige/krigesum.pyx
src/gstools/variogram/estimator.pyx

This PR adds fixes for complains from [cython-lint](https://github.com/MarcoGorelli/cython-lint) and adds a cython lint check in CI.
I also added the `lint` install flag for optional dependencies for linting (black, isort, pylint, cython-lint).
changes:
- added wheels for Python 3.12
- dropped support for Python 3.7 (EOL)
- linted Cython files with cython-lint
- use Cython 3 to build extensions

Python 3.12 support, Cython linting

---

src/gstools/covmodel/models.py

`Integral.spectral_density` raised a zero division error when evaluated at 0.
This fix calculates the limit value separately at the origin.

Integral model: separate calculation at origin for spectral density

---

.github/workflows/main.yml
CHANGELOG.md
pyproject.toml
src/gstools/covmodel/fit.py
src/gstools/field/plot.py
src/gstools/krige/base.py
src/gstools/transform/field.py

Finalize GSTools for v1.5.2
last minute fixes:
- remove universal2 wheels for macos (we already have intel and arm64 wheels and numpy also doesn't provide separate universal2 wheels)
- specify macos image versions in CI
- increase minimal matplotlib version to 3.7 (fixes radio button hack)
- minor pylint fixes for used-before-assignment issues

perpare v1.5.2

---

README.md
docs/source/index.rst
src/gstools/config.py
src/gstools/field/generator.py
src/gstools/field/summator.pyx
src/gstools/krige/base.py
src/gstools/krige/krigesum.pyx
src/gstools/variogram/estimator.pyx
src/gstools/variogram/variogram.py

As mentioned in #343, our very clean and elegant implementation of the conditional import of OpenMP is deprecated and this is my attend to find a new solution.

Drop deprecated conditional compilation
